import type { Metadata } from 'next'
import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'
import { LayoutProps } from './types'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: Readonly<LayoutProps>) {
  const { children } = props

  return (
    <html lang="en">
      <body>
        <div id="main-layout">
          {children}
        </div>
      </body>
    </html>
  )
}
